# Numpy

## 기본
ndarray : class, 같은 type의 값들로 구성, axis = 차원

### 속성

- ndarray.ndim : 차원수
- ndarray.shape : 데이터 모양
- ndarray.size : 전체 값 개수
- ndarray.dtype : 값의 type
- ndarray.itemsize : 각 값의 크기 (byte)

In [1]:
import numpy as np

ar1= np.arange(15).reshape (3,5)

ar1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
ar1.size

15

In [2]:
ar1.shape

(3, 5)

In [3]:
ar1.ndim

2

In [4]:
ar1.size

15

In [9]:
np.array(list(range(0,15))).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 생성

- np.array ( 리스트 ) 
- np.zeros (shape )  or np.ones , np.empty
- np.arrange (size) or np.arange (시작, 끝, 간격) 


In [5]:
np.array ( [1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Operations

### 기본
- 사칙연산 : 벡터* 스칼라  => 각 element와 스칼라 연산
- 각 element 에 적용되는 연산:  exp(), sqrt() .. 
- 벡터 * 벡터 => 일반 벡터연산이 아니고, 같은 위치의 element 끼리 연산
- 벡터 곱은 @
- += 도 동작함 

In [11]:
A = np.array( [[1,2], [3,4]])
B = np.array ( [[2,3], [4,5]])

A*4

array([[ 4,  8],
       [12, 16]])

In [12]:
np.sqrt(A)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [13]:
A*B

array([[ 2,  6],
       [12, 20]])

In [14]:
A@B

array([[10, 13],
       [22, 29]])

In [18]:
print(A)
A@np.array([1,2]).reshape(2,1)


[[1 2]
 [3 4]]


array([[ 7, 10]])

In [12]:
A+=3
A

array([[4, 5],
       [6, 7]])

### sum, max, min

In [19]:
A= np.random.randn(3,2)
A

array([[1.18235531, 1.40994133],
       [1.79440777, 0.59815694],
       [0.79147882, 0.92058155]])

In [20]:
A.sum()

6.6969217267685135

In [15]:
A.min()

-1.4649048983238424

### (중요) axis에 따른 연산

- 주요 파라메터 : axis, 차원 기준 
- sum (axis=0 ) : 첫번째 차원으로 합
- sum (axis=1 ) : 두번째 차원으로 합

In [16]:
B=np.arange(12).reshape (3,4)  # 첫번째 차원 =3개 element , 두번째 차원 =각기 element 는 4개 짜리 array
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
B.sum (axis=0) # 3개의 element 끼리 더함

array([12, 15, 18, 21])

In [18]:
B.mean (axis=1) # 2번째 차원의 4개의 element 끼리 평균

array([1.5, 5.5, 9.5])

In [19]:
B.max( axis=0)

array([ 8,  9, 10, 11])

## 과제 1 : 1부터 30까지 숫자로 (5,3,2) 3차원을 만든 뒤, 각 숫자에 0과1 사이의 random noise  을 곱한 결과를 출력하시오


과제 실행 위해 필요한 부분 (ex. import numpy as np )만 발췌해서, 답안지만 hw-02.ipynb 파일로 제출 

## Indexing, slicing


- 1차원 : element A[2],  범위 A[2:5]
- 2차원 : element B[2,3] , 범위 B [1:3, : ]   : 는 전체를 의미
- ...  :  x[1, 2, ...]  동일  x[1, 2, :, :, :]

In [23]:
A=np.arange (5, 15, 1)
A

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
A[1:3]

array([6, 7])

In [25]:
A[[2,3]]

array([7, 8])

In [28]:
A[3,]

8

In [26]:
B=np.arange(30).reshape((5,6))
B

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [27]:
B[3,2]

20

In [28]:
B[3, 2:4]

array([20, 21])

In [30]:
B[[0,1],[3,5]]

array([ 3, 11])

In [32]:
C=np.arange(1,46).reshape((5,3,3))
C

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45]]])

In [33]:
C[:,:,1]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26],
       [29, 32, 35],
       [38, 41, 44]])

In [34]:
C[:,1,:]

array([[ 4,  5,  6],
       [13, 14, 15],
       [22, 23, 24],
       [31, 32, 33],
       [40, 41, 42]])

In [33]:
C[...,1]

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25],
       [28, 31, 34],
       [37, 40, 43]])

## 과제 2 : np.arange(30).reshape((5,6)) 에서 짝수 컬럼 (0,2,4..) column 만 뽑아서 새로운 array를 만드시오

...

In [36]:
D = np.arange(30).reshape((5,6))
D

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [37]:
D[:,[0,2,4]]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

# Pandas

## dataframe 

2차원 구조, column 마다 다른 데이터 type, 일반 csv 데이터 구조 처리에 적합

### 만들기

- 딕셔너리로부터 만들기  :  {'컬럼명': [ 값, 값,.. ], '컬럼명': [값, 값, .. ] }
   pd.DataFrame (딕셔너리) 
   
- index와 column label (컬럼명)


In [40]:
import pandas as pd

dic= { 'gender' : [ 1, 2, 1,2], 'bloodtype': ["A", "B", "O", "AB"]}

df1= pd.DataFrame(dic)

df1

gender bloodtype
0       1         A
1       2         B
2       1         O
3       2        AB

- numpy array를 사용 가능 

  DataFrame ( array, index=index array, columns = 컬럼명)

In [41]:
dates = pd.date_range("20210309", periods=6)  # 날짜 생성
dates

DatetimeIndex(['2021-03-09', '2021-03-10', '2021-03-11', '2021-03-12',
               '2021-03-13', '2021-03-14'],
              dtype='datetime64[ns]', freq='D')

In [42]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

A         B         C         D
2021-03-09  0.633864  1.405114  0.178762  2.139276
2021-03-10 -1.862235  0.794555 -0.334370 -0.907299
2021-03-11 -2.286483 -0.485010  0.917442  0.881726
2021-03-12 -0.611601 -0.782840  0.668295 -1.433151
2021-03-13 -1.164593 -0.450034 -0.081096 -0.728527
2021-03-14  0.980624  2.383784  1.170688  1.337865

### 보기

In [43]:
df.head()

A         B         C         D
2021-03-09  0.633864  1.405114  0.178762  2.139276
2021-03-10 -1.862235  0.794555 -0.334370 -0.907299
2021-03-11 -2.286483 -0.485010  0.917442  0.881726
2021-03-12 -0.611601 -0.782840  0.668295 -1.433151
2021-03-13 -1.164593 -0.450034 -0.081096 -0.728527

In [44]:
df.tail(2)

A         B         C         D
2021-03-13 -1.164593 -0.450034 -0.081096 -0.728527
2021-03-14  0.980624  2.383784  1.170688  1.337865

In [45]:
df.index

DatetimeIndex(['2021-03-09', '2021-03-10', '2021-03-11', '2021-03-12',
               '2021-03-13', '2021-03-14'],
              dtype='datetime64[ns]', freq='D')

In [46]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

- 간단한 통계

In [47]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.718404  0.477595  0.419953  0.214982
std    1.318563  1.262546  0.591777  1.433484
min   -2.286483 -0.782840 -0.334370 -1.433151
25%   -1.687825 -0.476266 -0.016131 -0.862606
50%   -0.888097  0.172260  0.423529  0.076599
75%    0.322498  1.252474  0.855155  1.223830
max    0.980624  2.383784  1.170688  2.139276

- sort

In [48]:
df.sort_values(by="B")

A         B         C         D
2021-03-12 -0.611601 -0.782840  0.668295 -1.433151
2021-03-11 -2.286483 -0.485010  0.917442  0.881726
2021-03-13 -1.164593 -0.450034 -0.081096 -0.728527
2021-03-10 -1.862235  0.794555 -0.334370 -0.907299
2021-03-09  0.633864  1.405114  0.178762  2.139276
2021-03-14  0.980624  2.383784  1.170688  1.337865

### csv 파일 읽기

read_csv(파일명)

In [49]:
df=pd.read_csv("studentlist.csv", encoding="cp949")
df

name sex  age  grade absence bloodtype  height  weight  dept
0   김길동  남자   23      3       유         O   165.3    68.2     2
1   이미린  여자   22      2       무        AB   170.1    53.0     3
2   홍길동  남자   24      4       무         B   175.0    80.1     1
3   김철수  남자   23      3       무        AB   182.1    85.7     2
4   손세수  여자   20      1       유         A   168.0    49.5     1
5   박미희  여자   21      2       무         O   162.0    52.0     3
6   강수친  여자   22      1       무         O   155.2    45.3     2
7   이희수  여자   23      1       무         A   176.9    55.0     1
8   이철린  남자   23      3       무         B   178.5    64.2     1
9   방희철  남자   22      2       무         B   176.1    61.3     3
10  박수호  남자   24      4       유         O   167.1    62.0     3
11  임동민  남자   22      2       무        AB   180.0    75.8     3
12  김민수  남자   21      1       무         A   162.2    55.3     1
13  이희진  여자   23      3       무         O   176.1    53.1     2
14  김미진  여자   22      2       무         B   158.2    45.2     3
15  김동수  남자   24      4       유         B   168.6    70.2     1
16  여수근  남자   21      1       무         A   169.2    62.2     2

### indexing, selection

In [50]:
df[0:3]  # rows

name sex  age  grade absence bloodtype  height  weight  dept
0  김길동  남자   23      3       유         O   165.3    68.2     2
1  이미린  여자   22      2       무        AB   170.1    53.0     3
2  홍길동  남자   24      4       무         B   175.0    80.1     1

In [51]:
df[["age", "grade"]]  # column

age  grade
0    23      3
1    22      2
2    24      4
3    23      3
4    20      1
5    21      2
6    22      1
7    23      1
8    23      3
9    22      2
10   24      4
11   22      2
12   21      1
13   23      3
14   22      2
15   24      4
16   21      1

- index에 의한 참조 : iloc

In [52]:
df.iloc[1:5, 0:3]  

name sex  age
1  이미린  여자   22
2  홍길동  남자   24
3  김철수  남자   23
4  손세수  여자   20

In [53]:
df.iloc[ [1,2,4], [0, 2]]

name  age
1  이미린   22
2  홍길동   24
4  손세수   20

- label에 의한 참조 : loc

In [54]:
df.loc[0:3, ["age","grade"]]  

age  grade
0   23      3
1   22      2
2   24      4
3   23      3

- 값에 의한 참조 : boolean indexing , 조건에 맞는 row를 선택

In [55]:
df[ df["bloodtype"]=="B"]

name sex  age  grade absence bloodtype  height  weight  dept
2   홍길동  남자   24      4       무         B   175.0    80.1     1
8   이철린  남자   23      3       무         B   178.5    64.2     1
9   방희철  남자   22      2       무         B   176.1    61.3     3
14  김미진  여자   22      2       무         B   158.2    45.2     3
15  김동수  남자   24      4       유         B   168.6    70.2     1

In [57]:
print(df)
df["bloodtype"].isin( ["B", "A"] )

   name sex  age  grade absence bloodtype  height  weight  dept
0   김길동  남자   23      3       유         O   165.3    68.2     2
1   이미린  여자   22      2       무        AB   170.1    53.0     3
2   홍길동  남자   24      4       무         B   175.0    80.1     1
3   김철수  남자   23      3       무        AB   182.1    85.7     2
4   손세수  여자   20      1       유         A   168.0    49.5     1
5   박미희  여자   21      2       무         O   162.0    52.0     3
6   강수친  여자   22      1       무         O   155.2    45.3     2
7   이희수  여자   23      1       무         A   176.9    55.0     1
8   이철린  남자   23      3       무         B   178.5    64.2     1
9   방희철  남자   22      2       무         B   176.1    61.3     3
10  박수호  남자   24      4       유         O   167.1    62.0     3
11  임동민  남자   22      2       무        AB   180.0    75.8     3
12  김민수  남자   21      1       무         A   162.2    55.3     1
13  이희진  여자   23      3       무         O   176.1    53.1     2
14  김미진  여자   22      2       무         

0     False
1     False
2      True
3     False
4      True
5     False
6     False
7      True
8      True
9      True
10    False
11    False
12     True
13    False
14     True
15     True
16     True
Name: bloodtype, dtype: bool

In [52]:
df.loc [df["bloodtype"].isin( ["B", "A"] ), ["name", "age"] ]

name  age
2   홍길동   24
4   손세수   20
7   이희수   23
8   이철린   23
9   방희철   22
12  김민수   21
14  김미진   22
15  김동수   24
16  여수근   21

### operations

- 평균 등 : 객체.함수()

In [58]:
df['height'].mean()

170.03529411764703

## 과제 3 : 혈액형이 B형인 사람의 키의 평균을 구하시오